---
title: "svm_gene"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(e1071)
library(caret)
library(pROC)
library(readr)
data11tumors2 <- read_csv("../data/data11tumors2.csv")
```

```{r}
data11tumors2 %>% 
  distinct(Class)
```

```{r}
# Features (X) and Target (y)
X <- data11tumors2 %>% select(starts_with("D"))
y <- data11tumors2$Class


# Train/Test split (70% train, 30% test)
set.seed(494)
train_indices <- sample(1:nrow(data11tumors2), 0.8 * nrow(data11tumors2))
X_train <- X[train_indices, ]
y_train <- y[train_indices]
X_test <- X[-train_indices, ]
y_test <- y[-train_indices]
```

```{r}
# split_index <- createDataPartition(data11tumors2$Class, p = 0.8, list = FALSE)
# train_data <- data11tumors2[split_index, ]
# test_data <- data11tumors2[-split_index, ]
```

```{r}
# write_csv(train_data, "../data/train.csv")
# write_csv(test_data, "../data/test.csv")

```

```{r}
# # Perform hyperparameter tuning using tune.svm
# tune_result <- tune.svm(
#   x = X_train,
#   y = as.factor(y_train),
#   gamma = 2^(-3:3),  # Search range for gamma (RBF kernel)
#   cost = 2^(-3:3),   # Search range for cost parameter (C)
#   kernel = "radial",  # Use RBF kernel
#   tunecontrol = tune.control(cross = 4)  # 5-fold cross-validation
# )
# 
# # Best parameters
# best_params <- tune_result$best.parameters
# print(best_params)
# 
# # Train the SVM model with the best parameters
# svm_model_tuned <- svm(
#   x = X_train, 
#   y = as.factor(y_train), 
#   cost = best_params$cost,
#   gamma = best_params$gamma,
#   kernel = "radial",
#   probability = TRUE
# )

```

```{r}
# saveRDS(svm_model_tuned, "tuned_svm.rds")
```

```{r}
model_untuned <- svm(x = X_train, y = as.factor(y_train), kernel = "linear", cost = 0.1, gamma = 0.125, scale = TRUE)
```

```{r}
preds <- predict(model_untuned, X_test)

```

```{r}
confusionMatrix(preds, as.factor(y_test))
```

```{r}
svm_res <- read_csv("../data/svm_preds.csv")
knn_res <- read_csv("../data/knn_preds.csv") %>% mutate(preds = as.numeric(str_extract(Predicted, "\\d+"))) %>% select(preds)
knn_pca_res <- read_csv("../data/knn_pca_preds.csv")  %>% mutate(preds = as.numeric(str_extract(Predicted, "\\d+"))) %>% select(preds)
lasso_res <- read_csv("../data/lasso_preds.csv") %>% rename(preds= "preds %>% pull(.pred_class)")
```

```{r}
confusionMatrix(svm_res), as.factor(y_test))
```

```{r}
accuracy <- mean(svm_res == y_test)
print(accuracy)
```

```{r}

```
