---
title: "tam_svm_test"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(e1071)
library(caret)
library(pROC)
data(diamond)
```

```{r}
diamonds
```

```{r}
# Convert target variable to a binary classification problem
iris$Species <- as.factor(ifelse(iris$Species == "setosa", "setosa", "other"))

# Split data into training and testing sets
set.seed(494)
trainIndex <- createDataPartition(iris$Species, p = 0.8, list = FALSE)
trainData <- iris[trainIndex, ]
testData <- iris[-trainIndex, ]

# Train SVM model
svm_model <- svm(Species ~ ., data = trainData, kernel = "radial", probability = TRUE)

# Make predictions
predictions <- predict(svm_model, testData, probability = TRUE)
probabilities <- attr(predictions, "probabilities")[, "setosa"]

# Evaluate performance
conf_matrix <- confusionMatrix(predictions, testData$Species)
print(conf_matrix)

# Compute ROC curve and AUC
roc_curve <- roc(as.numeric(testData$Species == "setosa"), probabilities)
auc_value <- auc(roc_curve)
print(paste("AUC:", auc_value))

# Plot ROC curve
plot(roc_curve, main = "ROC Curve for SVM Model", col = "blue")

```

# 

```{r}
set.seed(123)
trainIndex <- createDataPartition(diamonds$cut, p = 0.8, list = FALSE)
train_data <- diamonds[strat_indices, ]
test_data <- diamonds[-strat_indices, ]
```

```{r}
svm_model <- svm(cut ~ ., data = train_data, kernel = "radial", probability = TRUE)


```

```{r}
saveRDS(svm_model, "svm_mod_diamonds.rds")
```

```{r}
predictions <- predict(svm_model, test_data, probability = TRUE)
```

```{r}
# Evaluate performance
conf_matrix <- confusionMatrix(predictions, test_data$cut)
print(conf_matrix)
```
